name: Guided Installation e2e tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This example triggers the workflow every 30 minutes
    - cron: '*/30 * * * *'

    
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        
      - name: Run Playwright tests
        run: |
          export ENV_SECRET_EMAIL=${{secrets.EMAIL}}
          export ENV_SECRET_PASSWORD=${{secrets.PASSWORD}}
          npx playwright test --reporter=html
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report/
          
      - name: Deploy to gitGithub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
